### PR TITLE
refresh captcha token after its get expired (120s)

### PR DESCRIPTION
**Pull request by MOwsianowski**
After 120s form cannot be successful submitted, because reCaptcha v3 token is expired. 
I added js interval each 120s to refresh the token.

### CODE REVIEW

**Comment by 9mido** [comment]
Maintainers, please add this logic to your other sample scripts also.

**Comment by MOwsianowski** [comment]
@9mido 
 > Maintainers, please add this logic to your other sample scripts also.

Done, also readme updated.

**Comment by 9mido** [comment]
@MOwsianowski thank you for being awesome great work!

**Comment by 9mido** [comment]
@MOwsianowski It would also be nice if you also added it to the homepage of this github project

**Comment by MOwsianowski** [comment]
@9mido 
Thanks also.
What do you mean about homepage? Homepage on GitHub is Readme itself, which is updated.

**Comment by kbytesys** [comment]
Hi! thank you for the PR! I will review it in few days.

We don't have any homepage.

We will generate a new pypi release after the PR is accepted.

**Comment by 9mido** [comment]
The code tab of https://github.com/kbytesys/django-recaptcha3

Gotcha sorry for the misunderstanding!

**Comment by Arussil** [comment]
Hello @kbytesys, there's still no new pypi version, there's an ETA for it or we can install from master directly to fix the problem? Thanks.

**Comment by kbytesys** [comment]
> Hello @kbytesys, there's still no new pypi version, there's an ETA for it or we can install from master directly to fix the problem? Thanks.

Hi! something is not working in my travis pipeline. I will investigate today/tomorrow.

**Pull request merged**
